export const currency = {
  1: "₺"
};

export const sikayetTipleri = {
  2: "Tesisat",
  3: "Tamirat",
  4: "Bina/Site",
  5: "Gayrimenkul",
  6: "Yönetim",
  7: "Görevli",
  50: "Diğer"
};

export const gayrimenkulDetails = {
  metrekare: "Metrekare",
  fiyat: "Fiyat",
  satis_fiyat: "Satış Fiyatı",
  portfoyno: "Portfoy No",
  dolu: "Dolu",
  tipi2: "Tipi 2",
  tipi: "Tipi",
  depozito: "Depozito",
  aidat: "Aidat",
  satilikkiralik: "Satılık - Kiralık",
  notlar: "Notlar",
  kapino: "Kapı No",
  sozlesmebitis: "Sözleşme Bitiş",
  afis: "Afiş",
  balkon: "Balkon",
  kat: "Kat",
  anahtar: "Anahtar",
  havuzyayinla: "Havuz Yayınla",
  oda_sayisi: "Oda Sayısı",
  ilgilidanisman: "İlgili Danışmann",
  acil: "Acil",
  esyali: "Eşyalı",
  sozlesmebaslangic: "Sözleşme Başlangıç",
  havuzacik: "Açık Havuz",
  sporalani: "Spor Alanı",
  asansor: "Asansör",
  jenerator: "Jeneratör",
  kres: "Kreş",
  hidrofor: "Hidrofor",
  sesyalitim: "Ses Yalıtım",
  uydu: "Uydu",
  oyunparki: "Oyun Parkı",
  siding: "Siding",
  kapici: "Kapıcı",
  sudeposu: "Su Deposu",
  kapaligaraj: "Kapalı Garaj",
  kablotv: "Kablo Tv",
  isiyalitim: "Isı Yalıtım",
  guvenlik: "Güvenlik",
  yanginmerdiveni: "Yangın Merdiveni",
  havuzkapali: "Kapalı Havuz",
  teniskortu: "Tenis Kortu",
  otopark: "Otopark",
  vadeli: "Vadeli",
  vade_toplam_fiyat: "Vade Toplam Fiyat",
  devir_fiyat: "Devir Fiyat",
  devir_pb: "Devir pb",
  ara_odeme: "Ara Ödeme",
  taksit_tutar: "Taksit Tutar",
  notlar: "Notlar",
  vade_sayisi: "Vade Sayısı",
  diafon: "Diafon",
  vestiyer: "Vestiyer",
  wifi: "Wi Fi",
  celikkapi: "Çelik Kapı",
  kiler: "Kiler",
  intercom: "İntercom",
  amerikanmutfak: "Amerikan Mutfak",
  ebevynbanyosu: "Ebeveyn Banyosu",
  fiber: "Fiber",
  gommedolap: "Gömme Dolap",
  jakuzi: "Jakuzi",
  firin: "Fırın",
  laminatmutfak: "Laminat Mutfak",
  camasirodasi: "Çamaşır Odası",
  asansor: "Asansör",
  alarmyangin: "Yangın Alarmı",
  adsl: "ADSL",
  mutfakdogalgazi: "Mutfak Doğalgazı",
  laminat: "Laminnat",
  ahsapdograma: "Ahşap Doğrama",
  marley: "Marley",
  ankastremutfak: "Ankastre Mutfak",
  kartonpiyer: "Kartonpiyer",
  pvcdograma: "PVC Doğrama",
  yerdenisitma: "Yerden Isıtma",
  giyinmeodasi: "Giyinme Odası",
  setustuocak: "Set Üstü Ocak",
  bulasikmakinesi: "Bulaşık Makinesi",
  sauna: "Sauna",
  buzdolabi: "Buzdolabı",
  camasir: "Çamaşır",
  kuvet: "Küvet",
  alarmhirsiz: "Alarm Hırsız",
  beyazesyali: "Beyaz Eşyalı",
  hiltonbanyo: "Hilton Banyo",
  sofben: "Şofben",
  seramik: "Seramik",
  panjur: "Panjur",
  ankastrefirin: "Ankastre Fırın",
  barbeku: "Barbekü",
  duvarkagidi: "Duvar Kağıdı",
  akilliev: "Akıllı Ev",
  spotisik: "Spot Işık",
  balkon: "Balkon",
  alaturkatuvalet: "Alaturka Tuvalet",
  mobilyali: "Mobilyalı",
  teras: "Teraas",
  somine: "Şömine",
  parke: "Parke",
  klima: "Klima",
  dusakabin: "Duşakabin",
  isicam: "Isıcam",
  boyali: "Boyalı"
};
